name: COBOL Check Automation

on:
    push:
      branches: [ main ]
      
jobs:
  cobol-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
          distribution: 'temurin'
          java-version: '17'

    - name: Create Zowe z/OSMF profile
      run: |
        /usr/local/bin/zowe profiles create zosmf-profile ci-profile \
        --host $ZOSMF_HOST \
        --port $ZOSMF_PORT \
        --user $ZOSMF_USER \
        --password $ZOSMF_PASSWORD \
        --reject-unauthorized $ZOSMF_REJECT_UNAUTHORIZED
      env:
        ZOSMF_HOST: ${{ secrets.ZOSMF_HOST }}
        ZOSMF_PORT: ${{ secrets.ZOSMF_PORT }}
        ZOSMF_USER: ${{ secrets.ZOSMF_USER }}
        ZOSMF_PASSWORD: ${{ secrets.ZOSMF_PASSWORD }}
        ZOSMF_REJECT_UNAUTHORIZED: false
        
    - name: Run Zowe command
      run: /usr/local/bin/zowe zos-jobs list jobs --rfj
